### ISSUE TITLE
Dockerfile for installation

### ISSUE THREAD

**Issue by akashsonth** [fzi-forschungszentrum-informatik/Semantic_Scene_Graph_Computation#1]
I installed Lanelet2 using the corresponding Docker file (https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/Dockerfile). I also installed CSV_Motion_Dataset_Loader by editing the same Docker file. When running the file `cli.py` from the Semantic_Scene_Graph_Computation, I get errors. I believe this is primarily because Lanelet2 uses Python 3.8. Is there a Dockerfile for the entire installation, or is there any way to go about the installation?

**Comment by max-zipfl** [comment]
Hi,
I just updated the repository, so that the files can be run by python3.8.
Please delete the current repo you have already downloaded and clone it again [1]. (I updated the root branch; "git pull" might not be enough and can cause errors).
[1] https://github.com/fzi-forschungszentrum-informatik/CSV_Motion_Dataset_Loader

I tried the workflow on the Docker file you suggested:
```
git clone https://github.com/fzi-forschungszentrum-informatik/Lanelet2.git # clone lanelet2
cd Lanelet2
docker build -t lanelet2 . # build docker; takes several minutes
docker run -it --rm lanelet2:latest /bin/bash
sudo apt update
sudo apt install python3-pip

mkdir script && cd script

# install csv loader
git clone https://github.com/fzi-forschungszentrum-informatik/CSV_Motion_Dataset_Loader.git
cd CSV_Motion_Dataset_Loader/
pip install -r requirements.txt
pip install .
cd ..

# install SSG
git clone https://github.com/fzi-forschungszentrum-informatik/Semantic_Scene_Graph_Computation.git
cd Semantic_Scene_Graph_Computation/
pip install -r requirements.txt

# test SSG
export PYTHONPATH=$PYTHONPATH:$(pwd)
python3 tests/testcomputation.py
```
